server:
  port: 8081


spring:
  application:
      name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8084

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-10372821.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oahwhrebo3hKimwe5d7
            client-secret: o87Vo65lTA7s42z5LMLWJdLFbTPqphoJJPcXgKcaC03QH01iJl-I8qyE_WZZSaMv

        provider:
          okta:
            issuer-uri: https://dev-10372821.okta.com/oauth2/default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-10372821.okta.com/oauth2/default
    audience: api://default