server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservice
  jpa:
    show-sql: true

  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8084
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-10372821.okta.com/oauth2/default
    audience: api://default