server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/rating/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-10372821.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahwhrebo3hKimwe5d7
    client-secret: o87Vo65lTA7s42z5LMLWJdLFbTPqphoJJPcXgKcaC03QH01iJl-I8qyE_WZZSaMv
    scopes: openid, profile, email, offline_access, device_sso, address, phone, internal